[pytest]
filterwarnings =
    ignore:ast.Str is deprecated.*:DeprecationWarning:werkzeug.routing.rules
    ignore:Attribute s is deprecated.*:DeprecationWarning:werkzeug.routing.rules
    ignore:Attribute s is deprecated.*:DeprecationWarning:ast
    ignore:Can't sort tables for DROP.*classes, users.*:sqlalchemy.exc.SAWarning
