"""Render the cleaned JSON intermediates (output/*.json) into MySQL-ready
INSERT statements.

Reads:  output/problems.json, output/problem_legacy_quest_map.json,
        output/problem_submissions.json  (produced by clean_and_transform.py)
Writes: output/data_problems.sql
        output/data_problem_legacy_quest_map.sql
        output/data_problem_submissions.sql
        output/data.sql (concatenation, in FK-safe order, for a single
                          `mysql ... < data.sql` run)

The `output/` directory is git-ignored (see repository .gitignore) because
the generated SQL can be a few MB once all ~26k submissions are included;
`schema.sql` and this generator script are the tracked, reviewable
artifacts. Run:

    python clean_and_transform.py
    python generate_sql.py
    mysql -u <user> -p <database> < schema.sql
    mysql -u <user> -p <database> < output/data.sql
"""
from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent / 'output'

BATCH_SIZE = 200


def sql_escape(value) -> str:
    if value is None:
        return 'NULL'
    if isinstance(value, bool):
        return '1' if value else '0'
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (list, dict)):
        value = json.dumps(value, ensure_ascii=False)
    text = str(value)
    text = text.replace('\\', '\\\\').replace("'", "\\'")
    text = text.replace('\r', '\\r').replace('\n', '\\n').replace('\x00', '')
    return f"'{text}'"


def render_insert(table: str, columns: list[str], rows: list[dict]) -> str:
    if not rows:
        return f'-- no rows for `{table}`\n'
    lines = [f"-- {len(rows)} rows for `{table}`"]
    col_list = ', '.join(f'`{c}`' for c in columns)
    for start in range(0, len(rows), BATCH_SIZE):
        batch = rows[start:start + BATCH_SIZE]
        tuples = []
        for row in batch:
            values = ', '.join(sql_escape(row.get(c)) for c in columns)
            tuples.append(f'({values})')
        lines.append(f"INSERT INTO `{table}` ({col_list}) VALUES\n" + ',\n'.join(tuples) + ';')
    return '\n'.join(lines) + '\n'


def load_json(name: str) -> list[dict]:
    with open(OUT_DIR / name, 'r', encoding='utf-8') as fh:
        return json.load(fh)


PROBLEM_COLUMNS = [
    'id', 'problem_no', 'concept', 'concept_group', 'title_en', 'title_cn', 'background',
    'background_source', 'description_en', 'description_cn', 'has_english',
    'input_format_en', 'output_format_en', 'input_format_cn', 'output_format_cn',
    'samples_json', 'samples_source', 'notes_json', 'difficulty', 'level',
    'star_difficulty', 'time_limit_ms', 'topic', 'reference_answer', 'template',
    'legacy_problem_name', 'legacy_author_user_id', 'is_active', 'created_at', 'updated_at',
]

QUEST_MAP_COLUMNS = [
    'problem_id', 'legacy_quest_id', 'legacy_quest_title_cn', 'required', 'sort_order',
]

TAG_COLUMNS = ['code', 'label', 'tag_type', 'color', 'sort_order']

SUBMISSION_COLUMNS = [
    'id', 'problem_id', 'legacy_user_id', 'legacy_username', 'legacy_student_name',
    'legacy_group_id', 'legacy_group_name', 'code_content', 'status', 'is_accepted',
    'compile_success', 'test_success', 'score_points', 'score_total', 'score_percent',
    'test_case_results_json', 'raw_judge_output', 'exec_time_ms', 'exec_memory_kb',
    'time_spent_seconds', 'self_confidence', 'legacy_error_name', 'returncode',
    'legacy_prev_solution_id', 'submitted_at',
]


def main():
    problems = load_json('problems.json')
    quest_map = load_json('problem_legacy_quest_map.json')
    submissions = load_json('problem_submissions.json')

    header = (
        "-- Auto-generated by generate_sql.py from output/*.json. Do not edit by hand;\n"
        "-- re-run `python clean_and_transform.py && python generate_sql.py` instead.\n"
        "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS = 0;\n\n"
    )
    footer = "\nSET FOREIGN_KEY_CHECKS = 1;\n"

    problems_sql = render_insert('problems', PROBLEM_COLUMNS, problems)
    quest_map_sql = render_insert('problem_legacy_quest_map', QUEST_MAP_COLUMNS, quest_map)
    submissions_sql = render_insert('problem_submissions', SUBMISSION_COLUMNS, submissions)

    (OUT_DIR / 'data_problems.sql').write_text(header + problems_sql + footer, encoding='utf-8')
    (OUT_DIR / 'data_problem_legacy_quest_map.sql').write_text(header + quest_map_sql + footer, encoding='utf-8')
    (OUT_DIR / 'data_problem_submissions.sql').write_text(header + submissions_sql + footer, encoding='utf-8')

    combined = header + problems_sql + '\n' + quest_map_sql + '\n' + submissions_sql + footer

    tags_path = OUT_DIR / 'problem_tags.json'
    tag_map_path = OUT_DIR / 'problem_tag_map.json'
    if tags_path.exists() and tag_map_path.exists():
        tags = load_json('problem_tags.json')
        raw_tag_map = load_json('problem_tag_map.json')
        # 显式分配 id：problem_tags 按 (tag_type, sort_order, code) 排序后编号，
        # 这样只要 generate_tags.py 的规则不变，重跑也会得到同样的 id，
        # 幂等可重复导入。
        tag_id_by_code = {t['code']: i + 1 for i, t in enumerate(tags)}
        tag_rows = [{**t, 'id': tag_id_by_code[t['code']]} for t in tags]
        tag_map_rows = [
            {'problem_id': row['problem_id'], 'tag_id': tag_id_by_code[row['tag_code']]}
            for row in raw_tag_map
        ]
        tags_sql = render_insert('problem_tags', ['id'] + TAG_COLUMNS, tag_rows)
        tag_map_sql = render_insert('problem_tag_map', ['problem_id', 'tag_id'], tag_map_rows)
        (OUT_DIR / 'data_problem_tags.sql').write_text(header + tags_sql + footer, encoding='utf-8')
        (OUT_DIR / 'data_problem_tag_map.sql').write_text(header + tag_map_sql + footer, encoding='utf-8')
        combined += '\n' + tags_sql + '\n' + tag_map_sql
        print(f'wrote {len(tag_rows)} tag rows, {len(tag_map_rows)} tag-map rows')
    else:
        print('problem_tags.json / problem_tag_map.json not found, skipping tag SQL (run generate_tags.py first)')

    combined += footer
    (OUT_DIR / 'data.sql').write_text(combined, encoding='utf-8')

    print(f'wrote {len(problems)} problem rows, {len(quest_map)} quest-map rows, {len(submissions)} submission rows')
    print(f'combined SQL: {OUT_DIR / "data.sql"} ({(OUT_DIR / "data.sql").stat().st_size / 1024:.1f} KB)')


if __name__ == '__main__':
    main()
